name: "Bug Report"
description: "Create a report to help us improve"
title: "[Issue]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior"
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen."
  
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
  
  - type: input
    id: os
    attributes:
      label: "OS"
      description: "e.g. Windows, Mac, Linux"
  
  - type: input
    id: browser
    attributes:
      label: "Browser"
      description: "e.g. chrome, safari"
  
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "e.g. 22"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
